### ISSUE TITLE
i would like to return as File when done crop thanks you

### ISSUE THREAD

**Issue by vannakyet** [deakjahn/crop_image#1]

**Comment by deakjahn** [comment]
Then save it for yourself. You can use

    data = await image.toByteData(format: ImageByteFormat.png)

to make a PNG out of it,

    bytes = data!.buffer.asUint8List()

to get the byte data and you can easily save that to a `File`:

    file.writeAsBytes(bytes, flush)

**Comment by vannakyet** [comment]
thanks you very much.

**Comment by muddi900** [comment]
I am getting this error when I try the above method:

```
E/FlutterJNI( 9460): Failed to decode image
E/FlutterJNI( 9460): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
E/FlutterJNI( 9460): 	at android.graphics.ImageDecoder.nCreate(Native Method)
E/FlutterJNI( 9460): 	at android.graphics.ImageDecoder.access$200(ImageDecoder.java:169)
E/FlutterJNI( 9460): 	at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:246)
E/FlutterJNI( 9460): 	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1754)
E/FlutterJNI( 9460): 	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1747)
E/FlutterJNI( 9460): 	at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:431)

════════ Exception caught by image resource service ════════════════════════════
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data

When the exception was thrown, this was the stack
#0      _futurize (dart:ui/painting.dart:5394:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:5262:12)
#2      instantiateImageCodec (dart:ui/painting.dart:2048:60)
<asynchronous suspension>
Path: /data/user/0/com.ilmdp.tennis_tennis_love/cache/image.png
```

**Comment by muddi900** [comment]
I was using `Uint64list`. It was resolved when I switched to 8 bits. Thanks.

**Comment by rikai-trongpq** [comment]
@deakjahn `toByteData` Im geting an error `The method 'toByteData' isn't defined for the type 'Image'.`

**Comment by expertdev-designer** [comment]
@vannakyet Please let me know how you do this bitmap to file

**Comment by Shubham-Narkhede** [comment]
`data = await image.toByteData(format: ImageByteFormat.png)`

what is this **image**.toByteData. From where we can create this image can you please let me know @deakjahn @vannakyet

**Comment by deakjahn** [comment]
A small error in the README. There are two **Image** types, `ui.Image` and the plain `Image`. The `toByteData()` function belongs to the first one. It will be fixed in the coming version.

**Comment by Shubham-Narkhede** [comment]
@deakjahn Thanks
