### ISSUE TITLE
How to reset aspectRatio?

### ISSUE THREAD

**Issue by prolongservices** [deakjahn/crop_image#12]
I want to reset aspectRatio,
for example if i set aspectRatio to 1:1 to make selection square.
but if i want to select in free size mode then how to reset?

**Comment by deakjahn** [comment]
I'm not sure I understand the question. If you don't want an aspect ratio, just don't set one. Actually, you need a controller to be able to set the aspect ratio in the first place, so if you don't use a controller at all, or if you use one but you don't specify the aspect ratio, you won't get it enforced.

**Comment by prolongservices** [comment]
Hi thank you for reply,

no no i m not asking for initial setup,

i want to reset aspect ratio after setting it,

for example
in my app i want to give option to select landscape aspect ratio, and if user is not comfortable in landscape and want to select in free size mode, then i want to give them option to reset aspect ratio so that they can select according to their need.

i hope now my question is clear

**Comment by deakjahn** [comment]
Pass null when you want to remove the aspect ratio. The controller's `aspectRatio` is a `double?`.

**Comment by prolongservices** [comment]
Yes i tried passing null, but its not working,

because in code if aspect ratio is coming null then its using previously passed value,

please correct me if i m wrong

**Comment by prolongservices** [comment]
![image](https://user-images.githubusercontent.com/59371022/181798080-e6b3dca1-c45f-4e11-8584-e6959e753a8c.png)

**Comment by prolongservices** [comment]
and here is the setter,

![image](https://user-images.githubusercontent.com/59371022/181798981-ba9e393f-2dde-43e5-90e8-65e9980e4780.png)

**Comment by deakjahn** [comment]
OK, I see. What if you change that last line in the setter to:

    else
      value = _CropControllerValue(null, value.crop);

Could you test this?
