### ISSUE TITLE
I want to get path of cropped image

### ISSUE THREAD

**Issue by Shubham-Narkhede** [deakjahn/crop_image#13]
Hello, I used this plugin this works well for me. When I crop the image and want to get the path of this image then get some problems. 

`Image image = await controller.croppedImage();`
`data = await image.toByteData(format: ImageByteFormat.png);`

I'm passing the image which i get from **controller.croppedImage()**. But they said **_The method 'toByteData' isn't defined for the type 'Image'._**. So can you please help me out with this problem?

**Comment by deakjahn** [comment]
There's no path, the cropping is done on the bitmap itself, that is, in memory. If you need it as a file, save it for yourself first.
