### ISSUE TITLE
SetState don't refresh image

### ISSUE THREAD

**Issue by marcio-ota** [deakjahn/crop_image#21]
I'm using:
```
child: CropImage(
    controller: controller,
    image: Image.memory(image),
    paddingSize: 25.0,
    alwaysMove: true,
    alwaysShowThirdLines: true,
)
```
But when change setState (() => image = NEW_IMAGE) keep old image

**Comment by marcio-ota** [comment]
If use a UniqueKey():

```
The following assertion was thrown by an image listener:
A CropController was used after being disposed.

```

**Comment by deakjahn** [comment]
Don't try to place the `UniqueKey()` call into your `build()` function, that will never work. You should have a variable in your state, initialize it to a key, and only use it in the build. But even then, I'd imagine that a `StreamBuilder()` is a much better solution, although it might be frightening if you never used it before. :-)

**Comment by marcio-ota** [comment]
The problem is that I can't refresh the screen (setstate), why controller is disposed...
can keep dispose manually ?

**Comment by deakjahn** [comment]
Yes. Don't let `CropImage` create its own controller automatically but provide your own. Then it's your responsibility to handle it and dispose of it at the end.
