### ISSUE TITLE
Cropped transparent PNG produce red background

### ISSUE THREAD

**Issue by DevMyWay** [deakjahn/crop_image#23]
hello,
and thank you for this cropper :)

i crop a PNG image in my Flutter web project.
i take the cropped bytes and set them to an Image widget but instead of transparent background i see a red background.
code:
    ui.Image bitmap = await controller.croppedBitmap();
    var data = await bitmap.toByteData(format: ui.ImageByteFormat.png);
    if (data == null) {
      //TODO: handle error
      return;
    }
    Uint8List pngBytes = data.buffer.asUint8List();

    setState(() {
      _croppedImage = pngBytes;
    });

and then show the bytes with:
Image.memory(_croppedImage!)

i also tried to save the bytes to a file and show the file with the same result.
i attach a PNGs files for debug :)

![logo](https://user-images.githubusercontent.com/30322509/231416750-640808e4-8fc4-4d6b-9d28-f36282ce100a.png)
![asset PNG](https://user-images.githubusercontent.com/30322509/231416930-efc468f2-225d-43d1-97c2-fed8151d0277.png)

**Comment by deakjahn** [comment]
Ooops, that seems to be the remants of a debug move at: https://github.com/deakjahn/crop_image/blob/1db6ca118894a6e1cd207a94cdbfd20d01be5ebc/lib/src/crop_controller.dart#L246

**Comment by monsieurtanuki** [comment]
@deakjahn Sorry about that, I didn't think about transparency!

**Comment by deakjahn** [comment]
Nothing to it. :-)
