### ISSUE TITLE
Type 'ImageDecoderCallback' not found.

### ISSUE THREAD

**Issue by MargaretLHP** [deakjahn/crop_image#32]
1.0.10.  
Running Gradle task 'assembleDebug'...
../../.pub-cache/hosted/pub.dev/crop_image-1.0.10/lib/src/crop_controller.dart:352:55: Error: Type 'ImageDecoderCallback' not found.
  ImageStreamCompleter loadImage(UiImageProvider key, ImageDecoderCallback decode) => OneFrameImageStreamCompleter(_loadAsync(key));
                                                      ^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/crop_image-1.0.10/lib/src/crop_controller.dart:352:55: Error: 'ImageDecoderCallback' isn't a type.
  ImageStreamCompleter loadImage(UiImageProvider key, ImageDecoderCallback decode) => OneFrameImageStreamCompleter(_loadAsync(key));
                                                      ^^^^^^^^^^^^^^^^^^^^

**Comment by deakjahn** [comment]
I can't reproducce this, it finds it for me. Which Flutter version do you use?

**Comment by MargaretLHP** [comment]
I use  => ImageStreamCompleter load(UiImageProvider key,DecoderCallback callback)
replace => ImageStreamCompleter loadImage(UiImageProvider key, ImageDecoderCallback decode)
then it works

**Comment by deakjahn** [comment]
You probably use a very old Flutter SDK then. The old approach before `ImageDecoderCallback` was deprecated in 3.7.0. We're at 3.10.6. now. Please, upgrade it -- as any other actively maintained package or plugin, we follow the development and changes of the Flutter SDK, too.

**Comment by MargaretLHP** [comment]
=>
Flutter 3.7.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 62bd79521d (4 months ago) • 2023-03-30 10:59:36 -0700
Engine • revision ec975089ac
Tools • Dart 2.19.6 • DevTools 2.20.1

**Comment by deakjahn** [comment]
Yes, that's a problem. We're at 3.10 now, not 3.7. You haven't upgraded your Flutter in quite some time -- in 4 months, actually, as it shows.

**Comment by Musaddiq625** [comment]
Ive fixed this
can you please accept this [pull request](https://github.com/deakjahn/crop_image/pull/36)
