### ISSUE TITLE
ImageDecoderCallback not found

### ISSUE THREAD

**Issue by rajeshkumarsahanee** [deakjahn/crop_image#33]
../../../.pub-cache/hosted/pub.dev/crop_image-1.0.10/lib/src/crop_controller.dart:352:55: Error: Type 'ImageDecoderCallback' not found.
  ImageStreamCompleter loadImage(UiImageProvider key, ImageDecoderCallback decode) => OneFrameImageStreamCompleter(_loadAsync(key));

**Comment by deakjahn** [comment]
Please, see https://github.com/deakjahn/crop_image/issues/32 that describes exactly the same issue. Only that it isn't really an issue at all. You're using an old Flutter SDK, it's time to upgrade.
