### ISSUE TITLE
CropGrid and Ract do not match after rotating the picture,

### ISSUE THREAD

**Issue by learning233** [deakjahn/crop_image#34]
select area - rotate =>wrong image
select area - rotate - select area => right image

**Comment by deakjahn** [comment]
Could you be a little bit more specific? I can't yet see what that's about...

**Comment by learning233** [comment]
> Could you be a little bit more specific? I can't yet see what that's about...
My mistake, I created a new controller to crop other images, without defining the rotation and defaultCrop parameters
