### ISSUE TITLE
Request a function that allows grid color separation

### ISSUE THREAD

**Issue by donghak-medi** [deakjahn/crop_image#35]
Hello, I'm using the package well! 

I'd like to ask you to add a function, would that be okay?

As for the current color, one grid color is applied to all external lines and internal lines, so could you add a function so that we can set the inner color separately? 

Thank you.

**Comment by deakjahn** [comment]
@donghak-medi 1.0.11 now supports three colors, added both for the internal lines and the corners.

**Comment by donghak-medi** [comment]
> @donghak-medi 1.0.11 now supports three colors, added both for the internal lines and the corners.

Wow, it works so well! 
Thank you for adding features!
