### ISSUE TITLE
When i crop a gif it will make it a png image

### ISSUE THREAD

**Issue by YawarOsman** [deakjahn/crop_image#40]
I am using the latest version at the moment `crop_image: ^1.0.11`.

I'm using this code for the crop:

```
  final bitmap = await controller.croppedBitmap();
  await bitmap.toByteData();
  ```

Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on macOS 11.7.10 20G1427 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 13.0)
    ✗ Flutter requires Xcode 14 or higher.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.83.1)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

**Comment by deakjahn** [comment]
The package itself doesn't save or convert to _any_ format. We have a small section at the end of the README to show you how you can save using Flutter's built-in functions but those belong to Flutter, not to this package. And yes, Flutter doesn't have built-in support for GIF, so if you want to save into this format, you'll have to find an image manipulation package that supports it.
