### ISSUE TITLE
The cropper is not repainting when we change any of the grid properties such as Color/InnerColor/Corner size ect

### ISSUE THREAD

**Issue by hedi-ghodhbane** [deakjahn/crop_image#49]
When trying to update any of the grid properties, it's not repainting. 

My case was simple, put a transparent color during loading an edge detecting algorithm, then reset the crop and put colors again to my main color. 

This is not working, because shouldRepaint is only comparing the old and new Crops as well as new and old isMoving property.

**Comment by deakjahn** [comment]
Fixed by https://github.com/deakjahn/crop_image/pull/50
