### ISSUE TITLE
Crop the image natively

### ISSUE THREAD

**Issue by hedi-ghodhbane** [deakjahn/crop_image#51]
Would be great if we can change the cropping logic to use native cropping. 
https://pub.dev/packages/native_image_cropper
We can use this for example, it might need some time to adapt the mecanisme to crop it natively, but we might achieve a huge performance optimization.
The experience right now takes quiet some time unfortunately

**Comment by deakjahn** [comment]
No, sorry, this won't happen. For two reasons:

* as the README says, "as it's written completely in Dart, it doesn't depend on any mobile package". This is a deliberate design choice that makes it run on the web, too.

* second, this package is not intended to actually cropp pictures. It's an UI element that allows your users to choose the _size_ they want to crop to. How you actually crop the image after that is entirely up to you. The package has a convenience function for you, yes, but it's in no way compulsory. You can use whatever platform mechanism you prefer instead.
